# Geosafe is very dependent on docker-geosafe orchestration to setup all of its dependencies
sudo: required

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - docker

env:
  - ALL_FILE: '/home/travis/build/kartoza/geosafe/scripts/travis/all.travis.geosafe.yml'

branches:
  only:
    - 2.6.x
    - 2.8.x

before_install:
  # install ansible
  - sudo apt-get -y update
  - sudo apt-get -y install libssl-dev
  - sudo pip install -r travis-requirements.txt
  # clone docker-geosafe
  - cd ../
  - git clone --depth=50 https://github.com/kartoza/docker-geosafe.git
  - cd docker-geosafe
  - git submodule init
  - git submodule sync
  - git submodule update
  # Go to root dir
  - cd ../

install:
  # setup files
  - pushd docker-geosafe
  - cd deployment
  - cp ${ALL_FILE} ansible/development/group_vars/all.yml
  # Run setup-ansible
  - make setup-ansible ANSIBLE_ARGS="--extra-vars='ansible_sudo_pass=\"\"' --extra-vars='pycharm_version=\"\"' --skip-tags=development"
  # show docker-compose.override.yml for debugging
  - cat docker-compose.override.yml
  - make build-geonode-core
  - make build
  - make up
  # Wait until database migrations ready
  - until make sync; do echo "Retrying"; sleep 5; done
  # Show container status
  - source compose.env.sh
  - docker-compose ps
  - popd

script:
  # Test Geosafe app
  - pushd geosafe
  # Run flake8
  - flake8 .
  # Run unittests
  - popd
  - pushd docker-geosafe/deployment
  - make geosafe-coverage-unittests-worker
  - sleep 10
  - make geosafe-coverage-test
  - make geosafe-coverage-unittests-worker-kill
  - popd

after_success:
  # Find coverage files
  - pushd docker-geosafe/src/geonode
  - coverage combine
  # Fix path (codecov.yml doesn't work)
  # Replace parent directory to travis directory, because we are running
  # coverage using docker mount
  - sed -i 's/usr\/src\/geosafe/home\/travis\/build\/kartoza\/geosafe/g' .coverage
  - codecov
  - popd
